ThatGuySam/doesitarm

- README.md
This PR orders the list of applications by alphabetical order
> Ordered lists

- README.md
Added pull request according to other related software and issues to minimize workload.
> #127 Add SubEthaEdit [New App]

- README.md
> Add Bartender

- README.md
> Add Arduino IDE

- README.md
> Adding Steam

- README.md
cc @luboslenco - Let me know if this is incorrect :slightly_smiling_face:
> Add ArmorPaint

- README.md
> Add Enpass

- README.md
This PR adds Filezilla and closes #17.
> Add Filezilla

- README.md
This PR adds Ulysses and closes #120
> Add Ulysses

- README.md
This PR adds Beyond Compare and closes #242
> Add Beyond Compare

- README.md
> Add DBeaver

- README.md
This PR adds Parallels Desktop and closes #255
> Add Parallels Desktop

- README.md
This PR adds Airmail and closes #236.
> Add Airmail

- README.md
This PR adds Welly BBS and closes #283.
> Add Welly BBS

- README.md
This PR adds Sketch, closes #46, and closes #287.
> Add Sketch

- README.md
This PR adds apps from the Eternal Storms Software and closes #277.
> Add Apps from Eternal Storms Software

- README.md
This PR adds PDF Viewer and closes #274.
> Add PDF Viewer

- README.md
Add BridgeTech Solutions currently supported apps
> Add BridgeTech Solutions currently supported apps

- README.md
I'm PM for these apps and both are optimized for Apple Silicon.
> Adds VPN Tracker 365 & Mail Designer 365

- README.md
Adding Telegram as per https://github.com/ThatGuySam/doesitarm/issues/52 :)
> Add Telegram

- README.md
As per https://github.com/ThatGuySam/doesitarm/issues/314 and https://github.com/ThatGuySam/doesitarm/issues/315 :)
> Adding Tidal, IVPN, Amphetamine

- README.md
Adding Signal as per https://github.com/ThatGuySam/doesitarm/issues/337 and Parcel as per this announcement on Twitter: https://twitter.com/parcel_app/status/1325751301322362880 (also confirmed on my own machine)
> Add Parcel and Signal

- README.md
> Add Post-it®

- README.md
As per https://github.com/ThatGuySam/doesitarm/issues/355
> Add VeraCrypt

- README.md
Full native support 👍
As per the release notes here: https://gpgtools.org/releases/gpgsuite/2020.2/release-notes.html?ni=1
Screenshot:
> Add GPG Suite

- README.md
Closes #362
Thanks for this great repo!
> Add eqMac to README.md

- README.md
Runs flawlessly on Rosetta 2, dev is working on native version but no ETA yet.
https://www.reddit.com/r/ledgerwallet/comments/jwzo3y/apple_m1_chip_ledger_live/gctrrxx/
> Add Ledger Live

- README.md
Full Apple Silicon support for all my Mac apps :-)
> Add Lighthouse16's apps to the list

- README.md
Fork has added native support in version 2.1.
> Fork has native support now

- README.md
I added Box Drive. 
I used the master branch.
https://github.com/ThatGuySam/doesitarm/issues/408
Thanks!
> Add Box Drive

- README.md
Updated Android Studio status, added native preview to IntelliJ IDEA
> Updated Android Studio status, added native preview to IntelliJ IDEA

- README.md
See Issue #426: SeaDrive 2.0.9 not working
> Added SeaDrive

- README.md
> Firefox 84 update

- README.md
Need to verify/test compile.
Related source issue: https://github.com/OpenISS/OpenISS/issues/72
> [OpenISS] add the initial entry

- README.md
Relative to issues #440 #439 #438
> Added Displays, TrashMe 3 and TunesArt

- README.md
JetBrains CLion, DataGrip, GoLand, PyCharm, RubyMine, and WebStorm
**Open Questions and Pre-Merge TODOs**
Source: JetBrains Toolbox, but also download links available on JetBrains website.
> Update JetBrains IDEs

- README.md
> Added Zwift

- README.md
> Add Logitech Options

- README.md
> Add Camo Studio

- README.md
Addresses https://github.com/ThatGuySam/doesitarm/issues/520
> Add Messenger to README

- README.md
> Add WebTorrent

- README.md
> Added M1 support for CleanShot X

- README.md
Full native since 22. Dec. 2020
> Update Flycut info

- README.md
As per: https://vivaldi.com/blog/vivaldi-fires-up-performance-2/
Native M1 support now added.
> Add native support for Vivaldi

- README.md
I removed BrandBook from the Mac App Store.
> Removed BrandBook

- README.md
Full Native Apple Silicon Support for Opera.
> Add Opera Web Browser

- README.md
I originally found out about this via [a Reddit post](https://www.reddit.com/r/SublimeText/comments/mlcqva/st4_native_apple_silicon_support/?utm_source=share&utm_medium=ios_app&utm_name=iossmf) but I thought referencing the release notes was better. There is a link to the Discord server at the top of the release notes page.
> Native support for Sublime Text

- README.md
Per #768. This is a big change so here's a handy PR to help nudge this one along 😉
> Spotify now native

- README.md
> Discord has native support with Canary build

- README.md
Per https://github.com/ThatGuySam/doesitarm/issues/820
Closes https://github.com/ThatGuySam/doesitarm/issues/820
> Add iStudiez Pro

- README.md
**The official name of the app**
BlurScreen App
**Is there a supported version available on a stable release channel?**
Yes
**Proposed App Status**
Yes, Native Apple Silicon Support
**Proposed App Category**
System Tools
Official App Landing Page
https://www.blurscreen.app
how it works
https://www.blurscreen.app/thankyou
> New App Request: BlurScreen App

- README.md
> Add Postico

- README.md
> Add Cocos Creator

- README.md
> Add AirMessage

- README.md
> Add Warp Terminal

- README.md
> EasyConnect works via Rosetta 2

- README.md
LTSpice Apple Silicon Native support. Details in the below issue
https://github.com/ThatGuySam/doesitarm/issues/421
> LTSpice Apple Silicon Native Support

- README.md
https://github.com/ThatGuySam/doesitarm/issues/495
> Anki support added

- assets/css/tailwind.css
- components/navbar.vue
**Navbar Update** :world_map:
- Added icon emojis for nav
- Merged 'Home' nav item with arm logo
- Added container to nav ad
- Attempt to improve responsiveness
**Build Successful**
https://deploy-preview-967--doesitarm.netlify.app/
> Navbar Update

- src/pages/index.astro
> Removed extra email input showing on landing page

- README.md
Update Microsoft Teams Status
related issue #932
> update Microsoft Teams

- README.md
The official name of the app
DisplayBuddy
Is there a supported version available on a stable release channel?
Yes
Proposed App Status
Yes, Native Apple Silicon Support
Proposed App Category
System Tools
Official App Landing Page
https://displaybuddy.app
> Add DisplayBuddy

- README.md
**The official name of the app**
Schedulist
**Is there a supported version available on a stable release channel?**
Yes
**Proposed App Status**
What's the current app status based off of current discussion or testing
You can check the different statused here: https://github.com/ThatGuySam/doesitarm/blob/master/README.md#legend
**Proposed App Category**
Productivity
**An Official App Download Page**
https://apps.apple.com/se/app/schedulist-to-do-planner/id1568459470?l=en
**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
> Add Schedulist

- README.md
The official name of the app
Aptakube
Is there a supported version available on a stable release channel?
Yes
Proposed App Status
✅ Yes, Native Apple Silicon Support
Proposed App Category
Developer Tools
Official App Landing Page
https://aptakube.com
Verification
> add Aptakube

- README.md
new domain for my app...
You can see that lighthouse16.com/quiet/ redirects to 5am.is/quiet/
> Update URL's for Quiet

- README.md
> adding contributor images to readme.md

- README.md
The official name of the app
Wave Terminal
Is there a supported version available on a stable release channel?
Yes
Proposed App Status
Yes, Native Apple Silicon Support
Proposed App Category
Developer Tools
Official App Landing Page
https://waveterm.dev
> added Wave Terminal
